version: '3.5'

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  postgres_data:  # Define the volume for PostgreSQL data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${POSTGRES_DATA_PATH}
  shared_static:

services:
  user-management:
    container_name: user-management
    build: ./userManagement
    env_file:
      - .env  # Adjust the path to your .env file if needed
    environment:
      - DATABASE_HOST=${POSTGRES_HOST}
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8000:8000"  # Adjust the port mapping as needed
    networks:
      - app-network
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: postgres_db
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Mount a volume for PostgreSQL data
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    volumes:
      - shared_static:/usr/share/nginx/html
    restart: unless-stopped

# Define other services here

