networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  #Usermanagement database volume
  usermanagement_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${USERMANAGEMENT_DATA_PATH}
  #Chat database volume
  chat_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${CHAT_DATA_PATH}
  shared_static:

services:
  #Container for the usermanagement database
  usermanagement_db:
    container_name: usermanagement_db
    image: postgres:13
    environment:
      POSTGRES_DB: ${USERMANAGEMENT_DATA_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - usermanagement_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
  #Container for the chat database
  chat_db:
    container_name: chat_db
    image: postgres:13
    environment:
      POSTGRES_DB: ${CHAT_DATA_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - chat_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  user-management:
    container_name: user-management
    build: ./userManagement
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=usermanagement_db
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - usermanagement_db
    restart: unless-stopped
  chat:
    container_name: chat
    build: ./chat
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=chat_db
    ports:
      - "8002:8002"
    networks:
      - app-network
    depends_on:
      - chat_db
    restart: unless-stopped

  frontend:
    container_name: frontend
    build: ./frontend
    environment:
      - VITE_IP=${IP}
    ports:
      - "3000:80"
    networks:
      - app-network
    volumes:
      - shared_static:/usr/share/nginx/html
    restart: unless-stopped

  solidity:
    container_name: solidity_service
    build: ./solidity
    environment:
      - ETHEREUM_NODE_URL=${ETHEREUM_NODE_URL}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - PRIVATE_KEY=${PRIVATE_KEY}
    # env_file:
      # - .env
    ports:
      - "8001:8001"
    networks:
      - app-network
    restart: unless-stopped

# Define other services here

