networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  usermanagement_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${USERMANAGEMENT_DATA_PATH}
  chat_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${CHAT_DATA_PATH}
  shared_static:
  online_games_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ONLINE_GAMES_DATA_PATH}
  solidity_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${SOLIDITY_DATA_PATH}
  images_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${IMAGES_DATA_PATH}
  remote_players_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${REMOTE_PLAYERS_DATA_PATH}

services:
  usermanagement_db:
    container_name: usermanagement_db
    image: postgres:13
    environment:
      POSTGRES_DB: ${USERMANAGEMENT_DATA_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - usermanagement_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
  chat_db:
    container_name: chat_db
    image: postgres:13
    environment:
      POSTGRES_DB: ${CHAT_DATA_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - chat_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
  remoteplayers_db:
    container_name: remoteplayers_db
    image: postgres:13
    environment:
      POSTGRES_DB: ${REMOTE_PLAYERS_DATA_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - remote_players_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
  online_games_db:
    container_name: online_games_db
    image: postgres:13
    environment:
      POSTGRES_DB: ${ONLINE_GAMES_DATA_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - online_games_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
  solidity_db:
    container_name: solidity_db
    image: postgres:13
    environment:
      POSTGRES_DB: ${SOLIDITY_DATA_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - solidity_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  user-management:
    container_name: user-management
    build: ./userManagement
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=usermanagement_db
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - usermanagement_db
    volumes:
      - images_data:/app/images
    restart: unless-stopped
  remote-players:
    container_name: remote-players
    build: ./remote_players
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=remoteplayers_db
    ports:
      - "8003:8003"
    networks:
      - app-network
    depends_on:
      - remoteplayers_db
    restart: unless-stopped
  online-games:
    container_name: online-games
    build: ./online_games
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=online_games_db
    ports:
      - "8004:8004"
    networks:
      - app-network
    depends_on:
      - online_games_db
    restart: unless-stopped
  chat:
    container_name: chat
    build: ./chat
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=chat_db
    ports:
      - "8002:8002"
    networks:
      - app-network
    depends_on:
      - chat_db
    restart: unless-stopped

  frontend:
    container_name: frontend
    build: ./frontend
    environment:
      - IP=${IP}
    ports:
      - "3000:443"
    networks:
      - app-network
    volumes:
      - shared_static:/usr/share/nginx/html
    restart: unless-stopped
    

  solidity:
    container_name: solidity_service
    build: ./solidity
    environment:
      - ETHEREUM_NODE_URL=${ETHEREUM_NODE_URL}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - POSTGRES_HOST=solidity_db
    env_file:
      - .env
    ports:
      - "8001:8001"
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - solidity_db

# Define other services here

