version: '3.5'

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  postgres_data:  # Define the volume for PostgreSQL data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${POSTGRES_DATA_PATH}
      
services:
  django:
    container_name: django
    image: django
    build: ./django
    env_file:
      - .env  # Adjust the path to your .env file if needed
    ports:
      - "8000:8000"  # Adjust the port mapping as needed
    networks:
      - app-network
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: postgres_db
    image: postgres:13
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Mount a volume for PostgreSQL data
    restart: unless-stopped

# Define other services here

