# Generated by Django 5.0.6 on 2024-05-31 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_users_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
