# Generated by Django 5.0.6 on 2024-06-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='test',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True),
        ),
    ]
